# Generated by Django 4.2.2 on 2023-06-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_capteur', models.CharField(max_length=50)),
                ('piece', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'capteur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField(db_column='date_')),
                ('heure', models.TimeField()),
                ('temperature', models.FloatField()),
            ],
            options={
                'db_table': 'donnee',
                'managed': False,
            },
        ),
    ]
