# Generated by Django 4.1.7 on 2023-06-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maison1',
            fields=[
                ('messageid', models.AutoField(db_column='messageID', primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50)),
                ('piece', models.CharField(max_length=100)),
                ('date_field', models.DateField(db_column='date_')),
                ('heure', models.TimeField()),
                ('temperature', models.FloatField()),
            ],
            options={
                'db_table': 'maison1',
                'managed': False,
            },
        ),
    ]
