# Generated by Django 4.2.2 on 2023-06-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_capteur', models.CharField(max_length=50)),
                ('piece', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'capteur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datte', models.DateField()),
                ('heure', models.TimeField()),
                ('temperature', models.FloatField()),
            ],
            options={
                'db_table': 'donnee',
                'managed': False,
            },
        ),
    ]
